### ISSUE TITLE
[ci] Enable TCP Integration Tests for Catloop LibOS in `demikernel-ci`

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#610]
## Context

We should enable TCP integration tests for Catloop LibOS in `demikernel-ci`.

In order to do so, we should close the following issues:

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/demikernel/issues/812
- [ ] https://github.com/microsoft/demikernel/issues/820
- [ ] https://github.com/microsoft/demikernel/issues/821
- [ ] https://github.com/microsoft/demikernel/issues/822
- [ ] https://github.com/microsoft/demikernel/issues/823
- [ ] https://github.com/microsoft/demikernel/issues/824
- [ ] https://github.com/microsoft/demikernel/issues/825
- [ ] https://github.com/microsoft/demikernel/issues/826
- [ ] https://github.com/microsoft/demikernel/issues/827
- [ ] https://github.com/microsoft/demikernel/issues/828
- [ ] https://github.com/microsoft/demikernel/issues/829
- [ ] https://github.com/microsoft/demikernel/issues/830
- [ ] https://github.com/microsoft/demikernel/issues/831
- [ ] https://github.com/microsoft/demikernel/issues/832
- [ ] https://github.com/microsoft/demikernel/issues/833
- [ ] https://github.com/microsoft/demikernel/issues/834
- [ ] https://github.com/microsoft/demikernel/issues/835
```
