### ISSUE TITLE
Depecrated warnings may cause build failures in integration

### ISSUE THREAD

**Issue by anandbonde** [microsoft/demikernel#878]
## Description
There are several deprecated functions in the Demikernel source code. Cargo build returns a non-zero value when there are warnings in the build. This may cause build integrations for some product groups (e.g. Bing) to fail.

## How to Reproduce

1. Build the demikernel source code.
2. Observe that there are build warnings for deprecated functions.

## Expected Behavior

There should be no build warnings.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/demikernel/issues/884
- [ ] https://github.com/microsoft/demikernel/issues/885
- [ ] https://github.com/microsoft/demikernel/issues/886
- [ ] https://github.com/microsoft/demikernel/issues/887
- [ ] https://github.com/microsoft/demikernel/issues/888
- [ ] https://github.com/microsoft/demikernel/issues/889
- [ ] https://github.com/microsoft/demikernel/issues/890
```

**Comment by ppenna** [comment]
This issue was fixed.
